import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const root=new URL('../',import.meta.url);
const html=fs.readFileSync(new URL('index.html',root),'utf8');
const catalog=JSON.parse(html.split('\n').find(line=>line.startsWith('const DATA=')).slice(11,-1)).catalog;
const window={};
let copied='';
let activeParts=[];
const context={window,document:{getElementById:()=>({querySelectorAll:()=>activeParts.map(textContent=>({textContent}))})},navigator:{clipboard:{writeText:async value=>{copied=value;}}}};
vm.runInNewContext(fs.readFileSync(new URL('scripts/static-demos.js',root),'utf8'),context);
vm.runInNewContext(fs.readFileSync(new URL('scripts/static-field-suggestions.js',root),'utf8'),context);
vm.runInNewContext(fs.readFileSync(new URL('scripts/static-demo-ui.js',root),'utf8'),context);
const formulaParts=markup=>[...markup.matchAll(/<p class="staticFormulaPart" data-copy-text="([^"]*)">/g)]
  .map(match=>match[1].replaceAll('&quot;','"').replaceAll('&#39;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&'));
assert.deepEqual(Object.keys(window.prontuarioStaticDemos).sort(),['abusivo','rifiuto','turno']);
const variants=window.prontuarioDemoCaseItems(catalog);
assert.deepEqual(Array.from(variants,item=>item.code),['G03-01','G03-02','G03-03','G03-04']);
assert.equal(new Set(variants.map(item=>item.id)).size,4);
assert.ok(variants.every(item=>item.demoBaseId==='rifiuto'&&item.demoBaseCode==='G03'&&item.payments.length===1));
variants.forEach((item,index)=>assert.strictEqual(item.payments[0],catalog.find(entry=>entry.id==='rifiuto').payments[index]));
assert.ok(html.includes('STATIC_LAYOUT.variantItems'));
assert.ok(html.includes("x.demoBaseId||x.id"));
assert.ok(!html.includes('id="caseGuide"'));
assert.ok(!html.includes('id="guidedPanel"'));
assert.ok(!html.includes('src="scripts/guide-ui.mjs"'));
const helpers={esc:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;'),sourceLink:()=>'',date:value=>value};
for(const item of [...variants,...catalog.filter(entry=>['abusivo','turno'].includes(entry.id))]){
  const demo=window.prontuarioStaticDemos[item.demoBaseId||item.id];
  assert.equal(item.demoBaseCode||item.code,demo.code);
  assert.equal(demo.formulaParts.length,demo.suggestions.length+1);
  assert.ok(demo.code==='G01'||demo.formulaParts.join(' ').includes('[…]'));
  assert.ok(!demo.formulaParts.join(' ').includes('{{'));
  assert.ok(demo.suggestions.every(group=>group.options.length>=2&&group.options.length<=3));
  assert.ok(demo.suggestions.every(group=>group.other===undefined&&demo.code==='G01'&&group.title==='Condizione della licenza'||/^(Altra|Altro) .*: \[…\]$/.test(group.other)));
  const rendered=window.prontuarioStaticDemoBody(item,'Taxi',helpers);
  assert.match(demo.title,/^Taxi(?:\:| abusivo\:)/);
  const ordered=['Normativa violata','Tabella importi','Sanzioni accessorie e punti','Testo orientativo del verbale','Suggerimenti e note operative'];
  for(let index=1;index<ordered.length;index++)assert.ok(rendered.indexOf(ordered[index-1])<rendered.indexOf(ordered[index]),`${item.code}: ${ordered[index]}`);
  assert.ok(rendered.includes('class="staticAmountsTable"'));
  assert.match(rendered,/Decurtazione punti patente<\/th><td>No<\/td>/);
  assert.ok(rendered.includes('<thead>'));
  assert.ok(rendered.includes('<tbody><tr>'));
  assert.ok(rendered.includes('<tfoot>'));
  assert.ok(rendered.includes('Misura ridotta'));
  assert.ok(rendered.includes('Entro 5 giorni'));
  assert.ok(rendered.includes('Limiti edittali'));
  for(const value of item.payments[0].slice(1,5))assert.ok(rendered.includes(value==='Procedura Prefetto'?'Prefetto':value),`${item.code}: importo ${value}`);
  if(item.demoVariant){
    for(const other of variants.filter(variant=>variant.id!==item.id))assert.ok(!rendered.includes(`€ ${other.payments[0][1]}`),`${item.code}: fascia diversa mostrata`);
    assert.ok(rendered.includes(item.demoVariant.municipalSuspension));
    assert.ok(rendered.includes(item.demoVariant.municipalPoints));
  }
  assert.ok(!rendered.includes(item.sanction),`${item.code}: sanzione duplicata`);
  assert.ok(!rendered.includes('CdS residuale per condizioni del titolo'));
  assert.ok(!rendered.includes('Importi CdS: PMR'));
  assert.ok(!rendered.includes('Applicare solo per una condizione della licenza/autorizzazione'));
  assert.ok(demo.normative.every(reference=>rendered.includes(reference)));
  for(const group of demo.suggestions)if(group.other)assert.ok(rendered.includes(group.other));
  const formula=rendered.match(/<div class="formulaText" id="formulaText">(.*?)<\/div>/s)?.[1];
  assert.ok(formula);
  const parts=formulaParts(formula);
  const copiedTemplate=parts.map((part,index)=>part+(index<parts.length-1?' […].':'')).join(' ');
  assert.ok(!formula.includes('Fonte del numero C.P.'),`${item.code}: suggerimento superfluo sul numero C.P.`);
  assert.deepEqual(parts,Array.from(window.prontuarioDemoFormulaParts(demo,item.demoVariant)),`${item.code}: formula approvata invariata`);
  if(item.demoVariant){
    assert.ok(formula.includes('C.O. (Centrale Operativa), consultata il […]'),`${item.code}: C.O. precedenti`);
    assert.ok(formula.includes('U.O. indicata in intestazione, consultata il […]'),`${item.code}: U.O. precedenti`);
    assert.ok(formula.includes('Altro ufficio o fonte consultata: […]'),`${item.code}: fonte libera precedenti`);
  }
  assert.match(copiedTemplate,/^(Alla guida|Utilizzava|Adibiva|Con il veicolo)/);
  assert.ok(copiedTemplate.length<1500,`${item.code}: testo orientativo eccessivo`);
  assert.doesNotMatch(copiedTemplate,/alle ore|targa|generalità|operanti/i);
  assert.match(copiedTemplate,/veicolo indicato/);
  assert.equal((formula.match(/class="staticFormulaChoices"/g)||[]).length,demo.suggestions.length);
  assert.match(formula,/Utilizzare la voce pertinente/);
  for(const group of demo.suggestions)if(group.other)assert.ok(formula.includes(group.other));
  if(item.demoVariant)assert.ok(formula.includes(item.demoVariant.previousFormula));
  assert.ok((formula.match(/class="staticFormulaChoices"/g)||[]).length>=demo.suggestions.length);
  for(const act of demo.acts)assert.ok(formula.includes(act.text));
  assert.ok(!formula.includes('Solo se eseguito:'));
  assert.equal((rendered.match(/class="staticOperationalUse"/g)||[]).length,1);
  assert.equal((rendered.match(/Solo se eseguito:/g)||[]).length,1);
  assert.ok(!rendered.includes('Diciture per atti effettivamente eseguiti'));
  assert.ok(rendered.includes('Copia testo orientativo'));
  assert.ok(rendered.includes('Uffici destinatari'));
}
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/Punti comunali: Non previsti per la prima violazione/);
assert.doesNotMatch(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/Punti comunali: 5 punti/);
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/Da accertamento presso \[…] del \[…] non risultavano precedenti pertinenti del titolare nel quinquennio/);
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/presso la C\.O\. \[…\]/);
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/presso la U\.O\. indicata in intestazione/);
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/Se la verifica è pendente, non usare questa formula/);
assert.match(window.prontuarioStaticDemoBody(variants[0],'Taxi',helpers),/Se il passeggero riferisce fatti senza formalizzarli, riportare nella relazione/);
assert.deepEqual(Array.from(window.prontuarioStaticDemos.rifiuto.suggestions[1].options),['Osservazione diretta degli operanti: […].','Dichiarazione acquisita con atto n. […].']);
assert.equal(window.prontuarioStaticDemos.rifiuto.suggestions[1].other,'Altra modalità di accertamento: […]');
assert.match(window.prontuarioStaticDemos.rifiuto.formulaParts[0],/^Alla guida del veicolo indicato, con C\.P\. n\. \[…\]/);
assert.deepEqual(Array.from(window.prontuarioStaticDemos.abusivo.suggestions[0].options),['Non aveva conseguito la licenza.','Esercitava con licenza sospesa, come da provvedimento […].','Esercitava con licenza revocata, come da provvedimento […].']);
assert.equal(window.prontuarioStaticDemos.abusivo.suggestions[0].other,undefined);
assert.ok(window.prontuarioStaticDemos.abusivo.suggestions[1].options.every(option=>!option.includes('prenotazione')));
assert.match(window.prontuarioStaticDemos.abusivo.suggestions[1].options[1],/richiesta di corsa.*prelevava il passeggero.*corrispettivo/);
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.suggestions[1].options.join(' '),/scritta «TAXI»/);
assert.match(window.prontuarioStaticDemos.abusivo.notes.join(' '),/La sola prenotazione non qualifica il servizio come taxi/);
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.formulaParts.join(' '),/esercitato da/i);
assert.equal(window.prontuarioStaticDemos.abusivo.formulaParts[0],'Adibiva a servizio taxi il veicolo indicato senza avere ottenuto la prescritta licenza:');
assert.equal(window.prontuarioStaticDemos.abusivo.formulaParts[1],'Il servizio era accertato mediante:');
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.formulaParts.join(' '),/Da accertamento presso|L’ufficio \[…\]/);
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.acts.map(act=>act.text).join(' '),/separato verbale n\./);
assert.match(window.prontuarioStaticDemos.abusivo.notes.join(' '),/entro 10 giorni al Prefetto del luogo della commessa violazione, ai sensi dell’art\. 210, comma 3, CdS/);
assert.match(window.prontuarioStaticDemoBody(catalog.find(item=>item.id==='abusivo'),'Taxi',helpers),/Non aveva conseguito la licenza/);
const g01Rendered=window.prontuarioStaticDemoBody(catalog.find(item=>item.id==='abusivo'),'Taxi',helpers);
const g01Instruction='Per licenza sospesa o revocata, sostituire la prima frase; non aggiungere l’alternativa a ‘senza avere ottenuto’.';
assert.ok(g01Rendered.indexOf('Esercitava con licenza revocata')<g01Rendered.indexOf(g01Instruction));
assert.ok(g01Rendered.indexOf(g01Instruction)<g01Rendered.indexOf('Il servizio era accertato mediante'));
assert.ok(!formulaParts(g01Rendered).join(' ').includes(g01Instruction),'G01: istruzione fuori dal testo copiato');
assert.equal((window.prontuarioStaticDemoBody(catalog.find(item=>item.id==='abusivo'),'Taxi',helpers).match(/class="staticInlinePlaceholder"/g)||[]).length,2);
assert.match(window.prontuarioStaticDemos.abusivo.notes.join(' '),/Se la licenza è sospesa o revocata, sostituire l’intera prima frase/);
assert.match(window.prontuarioStaticDemos.abusivo.notes.join(' '),/Titolo: indicare l’ufficio realmente consultato/);
assert.match(window.prontuarioStaticDemos.abusivo.notes.join(' '),/Precedenti: annotare ufficio o fonte consultata/);
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.suggestions[0].options.join(' '),/C\.P\./);
assert.match(window.prontuarioStaticDemos.turno.formulaParts[0],/turno \[…\] stabilito dall’atto vigente \[…\]/);
assert.doesNotMatch(window.prontuarioStaticDemos.turno.suggestions[0].options.join(' '),/risultava assente/i);
assert.match(window.prontuarioStaticDemos.turno.suggestions[0].options[1],/Non svolgeva il turno assegnato.*registro.*confermato dall’ufficio/);
assert.match(window.prontuarioStaticDemos.turno.notes.join(' '),/La sola assenza dal punto controllato non prova il mancato svolgimento del turno/);
assert.doesNotMatch(window.prontuarioStaticDemoBody(catalog.find(item=>item.id==='abusivo'),'Taxi',helpers),/Oltre 60 giorni/);
const turnoRendered=window.prontuarioStaticDemoBody(catalog.find(item=>item.id==='turno'),'Taxi',helpers);
assert.match(turnoRendered,/sospensione da determinare dall’ufficio/);
assert.match(turnoRendered,/La sospensione comunale è di 15, 30 o 60 giorni/);
for(const id of ['rifiuto','turno'])assert.ok(window.prontuarioStaticDemos[id].normative.some(reference=>reference.includes('Regolamento comunale – delibera C.C. n. 80/2005')&&reference.includes('comma 1')));
assert.ok(!window.prontuarioStaticDemos.abusivo.normative.some(reference=>reference.includes('Regolamento comunale')));
assert.match(window.prontuarioStaticDemos.rifiuto.formulaParts.join(' '),/Copia del presente verbale verrà inviata all'Ufficio Corso Pubblico\./);
assert.equal(window.prontuarioStaticDemos.rifiuto.acts.length,1);
assert.match(window.prontuarioStaticDemos.rifiuto.acts[0].text,/ritirato.*UMC.*via più breve.*avvertenza.*fermo.*separato verbale/s);
assert.match(window.prontuarioStaticDemos.rifiuto.acts[0].text,/luogo indicato dall’interessato/);
assert.match(window.prontuarioStaticDemos.turno.formulaParts.join(' '),/Copia del presente verbale verrà inviata all'Ufficio Corso Pubblico\./);
assert.doesNotMatch(window.prontuarioStaticDemos.abusivo.formulaParts.join(' '),/Corso Pubblico/);
activeParts=formulaParts(window.prontuarioStaticDemoBody(variants[1],'Taxi',helpers));
await window.copyProntuarioStaticDemo(()=>{});
assert.equal(copied,activeParts.map((part,index)=>part+(index<activeParts.length-1?' […].':'')).join(' '));
assert.ok(copied.includes('Un precedente pertinente del titolare nel quinquennio'));
assert.ok(!copied.includes('Altra circostanza'));
assert.ok(!copied.includes('Solo se eseguito:'));
console.log('Sei casi dimostrativi: tabella orizzontale singola, alternative nel corpo, copia e Corso Pubblico OK');
